[[appendix-i-fhirpath-function-translation]]
= Appendix I – FHIRPath Function Translation
:page-layout: 2018May
:sectnums:
:sectanchors:
:toc:

This appendix provides detailed mappings for each FHIRPath function in terms of the ELM output produced.

[[aggregate]]
== .aggregate()

X.aggregate(<iteration>, <init>) === Aggregate(<iteration>, <init>)

[[all]]
== .all()

X.all(<condition>) === AllTrue(X $this let a: <condition> where a return a)

[[allfalse]]
== .allFalse()

X.allFalse() === AllTrue(X A return not A)

[[alltrue-1]]
== .allTrue()

X.allTrue() === AllTrue(X)

[[anyfalse]]
== .anyFalse()

X.anyFalse() === AnyTrue(X A return not A)

[[anytrue-1]]
== .anyTrue()

X.anyTrue() === AnyTrue(X)

[[children-1]]
== .children()

.children(X) === Children(X)

[[combine-1]]
== .combine()

X.combine(Y) === Flatten(\{ X, Y })

[[conformsto]]
== .conformsTo()

X.conformsTo(Y) === FHIRSupport.ConformsTo(Y)

Note that this mapping relies on an external library, FHIRSupport to provide conformance validation checking.

[[contains-2]]
== .contains()

X.contains(Y) === PositionOf(Y, X) >= 0

[[count-1]]
== .count()

X.count() === Count(X)

[[descendents-1]]
== .descendents()

.descendents(X) === Descendents(X)

[[distinct-1]]
== .distinct()

X.distinct() === distinct X

[[empty]]
== .empty()

X.empty() === not exists X

[[endswith-1]]
== .endsWith()

X.endsWith(Y) === EndsWith(X, Y)

[[exists-1]]
== .exists()

X.exists() === exists X

X.exists(<condition>) === exists (X $this where <condition>)

[[first-1]]
== .first()

X.first() === First(X)

[[hasvalue]]
== .hasValue()

X.hasValue() === X is not null

[[iif]]
== .iif()

X.iif(Y) === if X then Y else null

X.iif(Y, Z) === if X then Y else Z

[[indexof-1]]
== .indexOf()

X.indexOf(Y) === PositionOf(Y, X) // Note carefully the order of arguments here, it’s the opposite of IndexOf

[[isboolean]]
== .isBoolean()

X.isBoolean() === IsBoolean(X)

[[isdistinct]]
== .isDistinct()

X.isDistinct() === Count(X) = Count(distinct X)

[[isdate]]
== .isDate()

X.isDate() === IsDate(X)

[[isdatetime]]
== .isDateTime()

X.isDateTime() === IsDateTime(X)

[[isdecimal]]
== .isDecimal()

X.isDecimal() === IsDecimal(X)

[[isinteger]]
== .isInteger()

X.isInteger() === IsInteger(X)

[[isquantity]]
== .isQuantity()

X.isQuantity() === IsQuantity(X)

[[istime]]
== .isTime()

X.isTime() === IsTime(X)

[[last-1]]
== .last()

X.last() === Last(X)

[[lastindexof]]
== .lastIndexOf()

X.lastIndexOf(Y) === LastPositionOf(Y, X) // Note carefully the order of arguments here, it’s the opposite of lastIndexOf.

[[length-2]]
== .length()

X.length() === Length(X)

[[matches-1]]
== .matches()

X.matches(Y) === Matches(X, Y)

[[memberof]]
== .memberOf()

X.memberOf(Y) === InValueSet(X, Y) // where Y is required to be a ValueSetRef

[[oftype]]
== .ofType()

X.ofType(T) === X $this where $this is T return $this as <type>

Note that the argument T is required to be a literal string, and is interpreted as the name of a type. For non-named-types, type specifier syntax applies.

[[not-1]]
== .not()

X.not() === not X

[[now-1]]
== .now()

now() === Now()

[[repeat]]
== .repeat()

X.repeat(<element>) === Repeat(X, <element>)

The type of X.repeat(<element>) is inferred as the type of:

X.select(<element>).select(<element>)

[[replace]]
== .replace()

X.replace(Y, Z) === Replace(X, Y, Z)

[[replacematches-1]]
== .replaceMatches()

X.replaceMatches(Y, Z) === ReplaceMatches(X, Y, Z)

[[select]]
== .select()

If the result type of <element> is not list-valued:

X.select(<element>) === X $this let a: <element> where a is not null return a

If the result type of <element> is list-valued:

X.select(<element>) === Flatten(X $this let a: <element> where a is not null return a)

[[single]]
== .single()

X.single() === singleton from X

[[skip-1]]
== .skip()

X.skip(Y) === Slice(X, Y, null)

[[startswith-1]]
== .startsWith()

X.startsWith(Y) === StartsWith(X, Y)

[[subsetof]]
== .subsetOf()

X.subsetOf(Y) === X included in Y

[[substring-1]]
== .substring()

X.substring(Y) === SubString(X, Y)

X.substring(Y, Z) === SubString(X, Y, Z)

[[subsumes]]
== .subsumes()

X.subsumes(Y) === Subsumes(X, Y)

[[subsumedby]]
== .subsumedBy()

X.subsumedBy(Y) === SubsumedBy(X, Y)

[[supersetof]]
== .supersetOf()

X.supersetOf(Y) === X includes Y

[[tail-1]]
== .tail()

X.tail() === Slice(X, 1, null)

[[take-1]]
== .take()

X.take(Y) === Slice(X, 0, Coalesce(Y, 0))

[[toboolean-1]]
== .toBoolean()

X.toBoolean() === ToBoolean(X)

[[tochars]]
== .toChars()

X.toChars() === ToChars(X)

[[todatetime-1]]
== .toDateTime()

X.toDateTime() === ToDateTime(X)

[[today-1]]
== .today()

today() === Today()

[[todecimal-1]]
== .toDecimal()

X.toDecimal() === ToDecimal(X)

[[tointeger-1]]
== .toInteger()

X.toInteger() === ToInteger(X)

[[tostring-1]]
== .toString()

X.toString() === ToString(X)

[[totime-1]]
== .toTime()

X.toTime() === ToTime(X)

[[trace]]
== .trace()

X.output(Y) === Trace(X, Y) // Add to ELM

[[where]]
== .where()

X.where(<condition>) === X $this where <condition>
