[[appendix-c-reference-implementations]]
= Appendix C – Reference Implementations
:page-layout: dev
:backend: xhtml
:sectnums:
:sectanchors:
:toc:
:page-standards-status: informative

As part of the Clinical Quality Framework effort, reference implementations of a CQL-to-ELM translator, a native ELM execution engine, and other CQL-related tools are maintained. This appendix provides a brief overview of where to find more information on these reference implementations.

[[cql-elm-translator-reference-implementation]]
== CQL-ELM Translator Reference Implementation

The CQL-to-ELM Translator is a reference implementation for the translation of text-based CQL library documents into an XML or JSON representation using the ELM. In addition to being developed and used as part of CQF pilots, the translator has been integrated into production authoring environments for both Clinical Decision Support and Clinical Quality Measurement. The implementation can also be used as the first step in a process to enable distribution, translation, execution, and integration of CQL-based quality artifacts.

The CQL-to-ELM Translator is licensed under the open source http://www.apache.org/licenses/LICENSE-2.0[Apache Version 2.0] license, and available as part of the clinical_quality_language project on GitHub: https://github.com/cqframework/clinical_quality_language, as well as a https://search.maven.org/search?q=g:info.cqframework[Maven Package] (https://oss.sonatype.org/content/repositories/snapshots/info/cqframework/[Snapshots]).

For an overview of the project, along with current status, refer to the following document:

https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/OVERVIEW.md

[[cql-execution-framework-reference-implementation]]
== CQL Execution Framework Reference Implementation

A reference implementation for executing CQL is currently under development. This reference implementation was used in CQF pilots and has been integrated into production eCQM testing tools.

The CQL execution framework is licensed under the open source Apache Version 2.0 license, and available as part of the clinical_quality_language project on GitHub: https://github.com/cqframework/cql-execution.

For an overview of the project along with current status, refer to the following document:

https://github.com/cqframework/cql-execution/blob/master/OVERVIEW.md

[[other-cql-related-tools]]
== Other CQL-related Tools

Other CQL-related tools such as a graphical CQL grammar parsetree viewer, a ModelInfo generator, and a CQL syntax highlighting plugin for https://atom.io/[Atom] are also available. The Clinical Quality Framework Initiative maintains a list of known Community Projects on the CQL Github Wiki:

https://github.com/cqframework/clinical_quality_language/wiki/Community-Projects


