[[appendix-c-reference-implementations]]
= Appendix C – Reference Implementations
:page-layout: 2017Jul
:sectnums:
:sectanchors:
:toc:

As part of the Clinical Quality Framework effort, reference implementations of a CQL-ELM translator, a native ELM execution engine, and other CQL-related tools are in progress. This appendix provides a brief overview of where to find more information on these reference implementations.

[[cql-elm-translator-reference-implementation]]
== CQL-ELM Translator Reference Implementation

The CQL-ELM Translator is a reference implementation for the translation of text-based CQL library documents into an XML or JSON representation using the ELM. The implementation is intended to be used in CQF pilots and eventually integrated into production authoring environments for both Clinical Decision Support and Clinical Quality Measurement. The implementation can also be used as the first step in a process to enable distribution, translation, execution, and integration of CQL-based quality artifacts.

The CQL-ELM Translator is licensed under the open source http://www.apache.org/licenses/LICENSE-2.0[Apache Version 2.0] license, and available as part of the clinical_quality_language project on GitHub: https://github.com/cqframework/clinical_quality_language.

For an overview of the project, along with current status, refer to the following document:

https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/OVERVIEW.md

[[cql-execution-framework-reference-implementation]]
== CQL Execution Framework Reference Implementation

A reference implementation for executing CQL is currently under development. This reference implementation is intended to be used in CQF pilots and eventually integrated into production eCQM testing and certification tools.

The CQL execution framework is licensed under the open source http://www.apache.org/licenses/LICENSE-2.0[Apache Version 2.0] license, and available as part of the clinical_quality_language project on GitHub: https://github.com/cqframework/clinical_quality_language.

For an overview of the project along with current status, refer to the following document:

https://github.com/cqframework/clinical_quality_language/blob/master/Src/coffeescript/cql-execution/OVERVIEW.md

[[other-cql-related-tools]]
== Other CQL-related Tools

Other CQL-related tools such as a graphical CQL grammar parsetree viewer, a ModelInfo generator, and a CQL syntax highlighting plugin for https://atom.io/[Atom] are also available.

These tools are licensed under the open source http://www.apache.org/licenses/LICENSE-2.0[Apache Version 2.0] license and available on GitHub:

* https://github.com/cqframework/clinical_quality_language
* https://github.com/cqframework/atom_cql_support

